# Generated by Django 5.2.17 on 2026-09-29 17:53

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "Sign in"), ("reset", "Password reset")],
                        max_length=10,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(
                blank=True,
                help_text="Google account id when signed up with Google",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_prefs",
            field=models.JSONField(
                blank=True, default=accounts.models.default_notification_prefs
            ),
        ),
        migrations.CreateModel(
            name="SavedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("telebirr", "Telebirr"), ("card", "Card")],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=40)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("brand", models.CharField(blank=True, max_length=20)),
                ("last4", models.CharField(blank=True, max_length=4)),
                ("expiry", models.CharField(blank=True, max_length=5)),
                ("holder", models.CharField(blank=True, max_length=80)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "created_at"],
            },
        ),
    ]
