# Generated by Django 5.2.17 on 2026-09-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("department", models.CharField(max_length=60)),
                ("kind", models.CharField(max_length=30)),
                ("bg", models.CharField(max_length=9)),
                ("sort", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort", "name"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("percent_off", models.PositiveSmallIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        help_text="Which illustration the site draws for this product",
                        max_length=30,
                    ),
                ),
                (
                    "bg",
                    models.CharField(
                        help_text="Card background colour, e.g. #E0F1FF", max_length=9
                    ),
                ),
                ("buy_price", models.PositiveIntegerField()),
                (
                    "was_price",
                    models.PositiveIntegerField(
                        blank=True, help_text="Set when on sale", null=True
                    ),
                ),
                (
                    "rent_rate",
                    models.PositiveIntegerField(
                        blank=True, help_text="Per day; empty = not rentable", null=True
                    ),
                ),
                ("rent_only", models.BooleanField(default=False)),
                (
                    "deposit",
                    models.PositiveIntegerField(
                        default=0, help_text="Refundable, rentals only"
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Units available to buy / rent now"
                    ),
                ),
                (
                    "sold_percent",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Flash-deal progress bar"
                    ),
                ),
                ("free_delivery", models.BooleanField(default=False)),
                (
                    "ships_in_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For items that are not in stock",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=60)),
                ("note", models.CharField(blank=True, max_length=120)),
                ("per_day", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_ons",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("product", "key")},
            },
        ),
        migrations.CreateModel(
            name="RentalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.PositiveSmallIntegerField()),
                ("price", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["days"],
                "unique_together": {("product", "days")},
            },
        ),
    ]
