# Generated by Django 5.2.17 on 2026-09-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=160)),
                ("bg", models.CharField(max_length=9)),
                (
                    "kind1",
                    models.CharField(help_text="Main illustration", max_length=30),
                ),
                (
                    "kind2",
                    models.CharField(help_text="Small illustration", max_length=30),
                ),
                ("sort", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("support", "Help with an order"),
                            ("sell", "Sell or list with us"),
                            ("careers", "Careers"),
                            ("other", "Something else"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "contact",
                    models.CharField(help_text="Phone or email", max_length=120),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=80)),
                ("summary", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(help_text="HTML")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="Simbatech", max_length=60)),
                ("city", models.CharField(default="Addis Ababa", max_length=60)),
                (
                    "address",
                    models.CharField(
                        default="Bole Road, near Edna Mall, Addis Ababa", max_length=160
                    ),
                ),
                ("phone", models.CharField(default="0911 000 000", max_length=20)),
                ("whatsapp", models.CharField(default="0911 000 000", max_length=20)),
                (
                    "support_email",
                    models.EmailField(default="hello@simbatech.et", max_length=254),
                ),
                ("hours", models.CharField(default="Mon–Sat, 8am–7pm", max_length=60)),
                (
                    "same_day_cutoff_hour",
                    models.PositiveSmallIntegerField(
                        default=16,
                        help_text="Orders before this hour (24h) can be delivered today",
                    ),
                ),
                ("pickup_ready_hours", models.PositiveSmallIntegerField(default=2)),
                (
                    "return_days",
                    models.PositiveSmallIntegerField(
                        default=7, help_text="Days to return a purchase"
                    ),
                ),
                (
                    "deposit_refund_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Days to refund a rental deposit after collection",
                    ),
                ),
                (
                    "warranty_default",
                    models.CharField(
                        default="12-month manufacturer's warranty", max_length=60
                    ),
                ),
                (
                    "damage_policy",
                    models.CharField(
                        default="Normal wear is fine. Damage beyond that is charged from the deposit, up to the excess shown on the product.",
                        max_length=200,
                    ),
                ),
                (
                    "pay_on_delivery_terms",
                    models.CharField(
                        default="Pay the driver by Telebirr or card when your order arrives. Orders over ETB 50,000 need a 20% deposit online.",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "store settings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="in_the_box",
            field=models.JSONField(
                blank=True, default=list, help_text='["Camera body", "Battery", ...]'
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="product",
            name="specs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[["Sensor", "24 MP full-frame"], ...]',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.CharField(
                blank=True, help_text='e.g. "12-month"', max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0, help_text="Recomputed from reviews"),
        ),
        migrations.AlterField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Recomputed from reviews"
            ),
        ),
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("qty", models.PositiveSmallIntegerField(default=1)),
                ("sort", models.PositiveSmallIntegerField(default=0)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.bundle",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The product booked for this item, if it is one we stock",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=80)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=60)),
                ("extra_price", models.PositiveIntegerField(default=0)),
                ("sort", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "id"],
                "unique_together": {("product", "key")},
            },
        ),
    ]
