# Generated by Django 5.2.17 on 2026-09-29 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=12, unique=True)),
                ("contact_name", models.CharField(max_length=80)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "fulfilment",
                    models.CharField(
                        choices=[
                            ("DELIVERY", "Delivery"),
                            ("PICKUP", "Pick up in store"),
                        ],
                        default="DELIVERY",
                        max_length=10,
                    ),
                ),
                (
                    "address",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the delivery address",
                        null=True,
                    ),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("delivery_window", models.CharField(blank=True, max_length=40)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TELEBIRR", "Telebirr"),
                            ("CARD", "Card"),
                            ("COD", "Pay on delivery"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("payment_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Placed"),
                            ("PACKED", "Packed"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLACED",
                        max_length=20,
                    ),
                ),
                ("purchases_total", models.PositiveIntegerField()),
                ("rentals_total", models.PositiveIntegerField()),
                ("delivery_fee", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField(default=0)),
                ("deposit_total", models.PositiveIntegerField(default=0)),
                (
                    "total",
                    models.PositiveIntegerField(
                        help_text="Amount charged now (excludes the refundable deposit)"
                    ),
                ),
                ("promo_code", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Placed"),
                            ("PACKED", "Packed"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("kind", models.CharField(max_length=30)),
                ("bg", models.CharField(max_length=9)),
                (
                    "mode",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("RENT", "Rent")], max_length=4
                    ),
                ),
                ("qty", models.PositiveSmallIntegerField()),
                ("unit_price", models.PositiveIntegerField()),
                ("line_total", models.PositiveIntegerField()),
                ("rent_start", models.DateField(blank=True, null=True)),
                ("rent_end", models.DateField(blank=True, null=True)),
                ("rent_days", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("add_ons", models.JSONField(blank=True, null=True)),
                ("deposit", models.PositiveIntegerField(default=0)),
                (
                    "rental_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("extended_days", models.PositiveSmallIntegerField(default=0)),
                ("extra_charge", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
