# Generated by Django 5.2.17 on 2026-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(
                blank=True, help_text='"chapa" or "simulated"', max_length=20
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Gateway transaction reference",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_label",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
